--- #YAML:1.0
name:               Linux-Pdeathsig
version:            0.00_02
abstract:           Perl interface to request a signal on parent death 
author:
    - Eric Clark <zerohp@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    repository:  http://github.com/eclark/Linux-Pdeathsig
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
